--  Generate SQL 
--  Version:                   	V5R1M0 010525 
--  Generated on:              	19.08.02 12:43:15 
--  Relational Database:       	BNK400DB 
--  Standards Option:          	DB2 UDB AS/400 
  
CREATE TABLE RSB59TB.BANKDPRT ( 
	PARTYID INTEGER NOT NULL DEFAULT 0 , 
	BIC_RCC CHAR(10) CCSID 1025 NOT NULL DEFAULT '' , 
	KINDDEPART CHAR(6) CCSID 1025 NOT NULL DEFAULT '' , 
	BIC_GENERAL FOR COLUMN BIC_GENERA CHAR(10) CCSID 1025 NOT NULL DEFAULT '' , 
	REGION CHAR(3) CCSID 1025 NOT NULL DEFAULT '' , 
	PLACE CHAR(6) CCSID 1025 NOT NULL DEFAULT '' , 
	CHECKALG SMALLINT NOT NULL DEFAULT 0 , 
	CHECKDATA CHAR(13) CCSID 1025 NOT NULL DEFAULT '' , 
	BLNC_RCC CHAR(4) CCSID 1025 NOT NULL DEFAULT '' , 
	"LOCK" CHAR(1) CCSID 1025 NOT NULL DEFAULT '' , 
	CORACC CHAR(26) CCSID 1025 NOT NULL DEFAULT '' , 
	REPT CHAR(1) CCSID 1025 NOT NULL DEFAULT '' , 
	VKEY CHAR(9) CCSID 1025 NOT NULL DEFAULT '' , 
	NOTBANK CHAR(1) CCSID 1025 NOT NULL DEFAULT '' , 
	RESERVE CHAR(89) CCSID 1025 NOT NULL DEFAULT '' ) ; 
  
LABEL ON TABLE RSB59TB.BANKDPRT 
	IS 'BANKDPRT.DBT' ; 
  
LABEL ON COLUMN RSB59TB.BANKDPRT 
( PARTYID IS 'INT4' , 
	BIC_RCC IS 'ZSTRING' , 
	KINDDEPART IS 'ZSTRING' , 
	BIC_GENERAL IS 'ZSTRING' , 
	REGION IS 'ZSTRING' , 
	PLACE IS 'ZSTRING' , 
	CHECKALG IS 'INT2' , 
	CHECKDATA IS 'ZSTRING' , 
	BLNC_RCC IS 'ZSTRING' , 
	"LOCK" IS 'STRING' , 
	CORACC IS 'ZSTRING' , 
	REPT IS 'STRING' , 
	VKEY IS 'ZSTRING' , 
	NOTBANK IS 'STRING' , 
	RESERVE IS 'ZSTRING' ) ; 
  
LABEL ON COLUMN RSB59TB.BANKDPRT 
( PARTYID TEXT IS 'хдемрхтхйюрнп ясаэейрю' , 
	BIC_RCC TEXT IS 'ахй пйж' , 
	KINDDEPART TEXT IS 'бхд нрдекемхъ аюмйю он жа' , 
	BIC_GENERAL TEXT IS 'йнд цпсоош' , 
	REGION TEXT IS 'пецхнм б йкюяяхтхйюжхх жа' , 
	PLACE TEXT IS 'мюяекеммши осмйр б йкюяяхтхйюжхх жа' , 
	CHECKALG TEXT IS 'юкцнпхрл опнбепйх яверю' , 
	CHECKDATA TEXT IS 'дюммше дкъ опнбепйх яверю' , 
	BLNC_RCC TEXT IS 'аюкюмянбши явер б пйж' , 
	"LOCK" TEXT IS 'опхгмюй акнйхпнбйх' , 
	CORACC TEXT IS 'йнпявер' , 
	REPT TEXT IS 'опхгмюй бшбндю оепевмъ' , 
	VKEY TEXT IS 'смхйюкэмши йкчв' , 
	NOTBANK TEXT IS 'опхгмюй меаюмйнбяйни йпедхрмни нпц.' , 
	RESERVE TEXT IS 'пегепб' ) ; 
  
CREATE TABLE RSB59TB.PARTY ( 
	PARTYID INTEGER NOT NULL DEFAULT 0 , 
	IOWNERKIND SMALLINT NOT NULL DEFAULT 0 , 
	LEGALFORM SMALLINT NOT NULL DEFAULT 0 , 
	SHORTNAME CHAR(21) CCSID 1025 NOT NULL DEFAULT '' , 
	NAME CHAR(81) CCSID 1025 NOT NULL DEFAULT '' , 
	ADDNAME CHAR(51) CCSID 1025 NOT NULL DEFAULT '' , 
	RESERVED3 CHAR(16) CCSID 1025 NOT NULL DEFAULT '' , 
	OKPO CHAR(16) CCSID 1025 NOT NULL DEFAULT '' , 
	NOTRESIDENT FOR COLUMN NOTRESIDEN CHAR(1) CCSID 1025 NOT NULL DEFAULT '' , 
	SUPERIOR INTEGER NOT NULL DEFAULT 0 , 
	CHANGE_DATE FOR COLUMN CHANGE_D@0 DATE NOT NULL DEFAULT CURRENT_DATE , 
	CHANGE_DATEPREV FOR COLUMN CHANGE_D@1 DATE NOT NULL DEFAULT CURRENT_DATE , 
	LOCKED CHAR(1) CCSID 1025 NOT NULL DEFAULT '' , 
	TAXINSTITUTION FOR COLUMN TAXINSTITU INTEGER NOT NULL DEFAULT 0 , 
	TAXREGDATE DATE NOT NULL DEFAULT CURRENT_DATE , 
	COUNTRY CHAR(4) CCSID 1025 NOT NULL DEFAULT '' , 
	REPUBLIC CHAR(31) CCSID 1025 NOT NULL DEFAULT '' , 
	REGION CHAR(12) CCSID 1025 NOT NULL DEFAULT '' , 
	NUMCORPS CHAR(6) CCSID 1025 NOT NULL DEFAULT '' , 
	HOUSE CHAR(6) CCSID 1025 NOT NULL DEFAULT '' , 
	FLAT CHAR(6) CCSID 1025 NOT NULL DEFAULT '' , 
	RESERVED2 CHAR(1) CCSID 1025 NOT NULL DEFAULT '' , 
	PLACE CHAR(31) CCSID 1025 NOT NULL DEFAULT '' , 
	POSTINDEX CHAR(16) CCSID 1025 NOT NULL DEFAULT '' , 
	ADDRESS CHAR(81) CCSID 1025 NOT NULL DEFAULT '' , 
	PHONENUMBER FOR COLUMN PHONENUM@0 CHAR(25) CCSID 1025 NOT NULL DEFAULT '' , 
	PHONENUMBER2 FOR COLUMN PHONENUM@1 CHAR(25) CCSID 1025 NOT NULL DEFAULT '' , 
	FAX CHAR(25) CCSID 1025 NOT NULL DEFAULT '' , 
	TELEGRAPH CHAR(8) CCSID 1025 NOT NULL DEFAULT '' , 
	TELEXNUMBER FOR COLUMN TELEXNUMBE CHAR(25) CCSID 1025 NOT NULL DEFAULT '' , 
	E_MAIL CHAR(81) CCSID 1025 NOT NULL DEFAULT '' , 
	SYSTYPE CHAR(17) CCSID 1025 NOT NULL DEFAULT '' , 
	USERTYPE CHAR(17) CCSID 1025 NOT NULL DEFAULT '' , 
	USERFIELD1 CHAR(121) CCSID 1025 NOT NULL DEFAULT '' , 
	USERFIELD2 CHAR(41) CCSID 1025 NOT NULL DEFAULT '' , 
	USERFIELD3 CHAR(81) CCSID 1025 NOT NULL DEFAULT '' , 
	USERFIELD4 CHAR(81) CCSID 1025 NOT NULL DEFAULT '' , 
	RS_MAIL_COUNTRY FOR COLUMN RS_MAIL_CO SMALLINT NOT NULL DEFAULT 0 , 
	RS_MAIL_REGION FOR COLUMN RS_MAIL_RE SMALLINT NOT NULL DEFAULT 0 , 
	RS_MAIL_NODE FOR COLUMN RS_MAIL_NO SMALLINT NOT NULL DEFAULT 0 , 
	STREET CHAR(25) CCSID 1025 NOT NULL DEFAULT '' , 
	NRCOUNTRY CHAR(4) CCSID 1025 NOT NULL DEFAULT '' , 
	RESERVE CHAR(171) CCSID 1025 NOT NULL DEFAULT '' ) ; 
  
--  SQL150A   30   System trigger QSYS_TRIG_RSB59TB____PARTY______000001 in RSB59TB ignored. 
--  SQL150A   30   System trigger QSYS_TRIG_RSB59TB____PARTY______000002 in RSB59TB ignored. 
LABEL ON TABLE RSB59TB.PARTY 
	IS 'PARTY.DBT' ; 
  
LABEL ON COLUMN RSB59TB.PARTY 
( PARTYID IS 'INT4' , 
	IOWNERKIND IS 'INT2' , 
	LEGALFORM IS 'INT2' , 
	SHORTNAME IS 'ZSTRING' , 
	NAME IS 'ZSTRING' , 
	ADDNAME IS 'ZSTRING' , 
	RESERVED3 IS 'ZSTRING' , 
	OKPO IS 'ZSTRING' , 
	NOTRESIDENT IS 'STRING' , 
	SUPERIOR IS 'INT4' , 
	CHANGE_DATE IS 'BDATE' , 
	CHANGE_DATEPREV IS 'BDATE' , 
	LOCKED IS 'STRING' , 
	TAXINSTITUTION IS 'INT4' , 
	TAXREGDATE IS 'BDATE' , 
	COUNTRY IS 'ZSTRING' , 
	REPUBLIC IS 'ZSTRING' , 
	REGION IS 'ZSTRING' , 
	NUMCORPS IS 'ZSTRING' , 
	HOUSE IS 'ZSTRING' , 
	FLAT IS 'ZSTRING' , 
	RESERVED2 IS 'STRING' , 
	PLACE IS 'ZSTRING' , 
	POSTINDEX IS 'ZSTRING' , 
	ADDRESS IS 'ZSTRING' , 
	PHONENUMBER IS 'ZSTRING' , 
	PHONENUMBER2 IS 'ZSTRING' , 
	FAX IS 'ZSTRING' , 
	TELEGRAPH IS 'ZSTRING' , 
	TELEXNUMBER IS 'ZSTRING' , 
	E_MAIL IS 'ZSTRING' , 
	SYSTYPE IS 'ZSTRING' , 
	USERTYPE IS 'ZSTRING' , 
	USERFIELD1 IS 'ZSTRING' , 
	USERFIELD2 IS 'ZSTRING' , 
	USERFIELD3 IS 'ZSTRING' , 
	USERFIELD4 IS 'ZSTRING' , 
	RS_MAIL_COUNTRY IS 'INT2' , 
	RS_MAIL_REGION IS 'INT2' , 
	RS_MAIL_NODE IS 'INT2' , 
	STREET IS 'ZSTRING' , 
	NRCOUNTRY IS 'ZSTRING' , 
	RESERVE IS 'ZSTRING' ) ; 
  
LABEL ON COLUMN RSB59TB.PARTY 
( PARTYID TEXT IS 'бмсрпеммхи хдемрхтхйюрнп' , 
	IOWNERKIND TEXT IS 'йнд бкюдекэжю' , 
	LEGALFORM TEXT IS 'бхд (1-нпцюмхгюжхъ, 2-тхг.кхжн)' , 
	SHORTNAME TEXT IS 'янйпюыеммне мюгбюмхе' , 
	NAME TEXT IS 'онкмне мюхлемнбюмхе' , 
	ADDNAME TEXT IS 'днонкмхрекэмне мюгбюмхе' , 
	RESERVED3 TEXT IS 'хмм б PARTCODE.DBT' , 
	OKPO TEXT IS 'йнд нйон=хмм' , 
	NOTRESIDENT TEXT IS 'опхгмюй мепегхдемрмнярх' , 
	SUPERIOR TEXT IS 'хдемрхтхйюрнп бшьеярнъыеи нпцюмхгюжх' , 
	CHANGE_DATE TEXT IS 'дюрю онякедмецн хглемемхъ' , 
	CHANGE_DATEPREV TEXT IS 'дюрю опедонякедмецн хглемемхъ' , 
	LOCKED TEXT IS 'опхгмюй акнйхпнбйх' , 
	TAXINSTITUTION TEXT IS 'мюкнцнбне свпефдемхе' , 
	TAXREGDATE TEXT IS 'дюрю пецхярпюжхх б мюкнц.хмяоейжхх' , 
	COUNTRY TEXT IS 'йнд ярпюмш' , 
	REPUBLIC TEXT IS 'пеяосакхйю' , 
	REGION TEXT IS 'накюярэ' , 
	NUMCORPS TEXT IS 'йнпося' , 
	HOUSE TEXT IS 'днл' , 
	FLAT TEXT IS 'йбюпрхпю' , 
	RESERVED2 TEXT IS 'онйю ме хяонкэгсеряъ' , 
	PLACE TEXT IS 'мюяекеммши осмйр' , 
	POSTINDEX TEXT IS 'онврнбши хмдейя' , 
	ADDRESS TEXT IS 'онврнбши юдпея' , 
	PHONENUMBER TEXT IS 'мнлеп рекетнмю' , 
	PHONENUMBER2 TEXT IS 'днонкмхрекэмши мнлеп рекетнмю' , 
	FAX TEXT IS 'тюйя' , 
	TELEGRAPH TEXT IS 'рекецпют' , 
	TELEXNUMBER TEXT IS 'рекейя' , 
	E_MAIL TEXT IS 'юдпея щкейрпнммни онврш' , 
	SYSTYPE TEXT IS 'яхярелмши рхо' , 
	USERTYPE TEXT IS 'онкэгнбюрекэяйхи рхо' , 
	USERFIELD1 TEXT IS 'онкэгнбюрекэяйне онке' , 
	USERFIELD2 TEXT IS 'онкэгнбюрекэяйне онке' , 
	USERFIELD3 TEXT IS 'онкэгнбюрекэяйне онке' , 
	USERFIELD4 TEXT IS 'онкэгнбюрекэяйне онке' , 
	RS_MAIL_COUNTRY TEXT IS 'RS-MAIL, йнд ярпюмш' , 
	RS_MAIL_REGION TEXT IS 'RS-MAIL, йнд пюинмю' , 
	RS_MAIL_NODE TEXT IS 'RS-MAIL, мнлеп сгкю' , 
	STREET TEXT IS 'скхжю' , 
	NRCOUNTRY TEXT IS 'йнд ярпюмш мепегхдемрю' , 
	RESERVE TEXT IS 'пегепб' ) ; 
  
CREATE TABLE RSB59TB.PARTCODE ( 
	PARTYID INTEGER NOT NULL DEFAULT 0 , 
	CODEKIND SMALLINT NOT NULL DEFAULT 0 , 
	CODE CHAR(36) CCSID 1025 NOT NULL DEFAULT '' , 
	RESERVE CHAR(100) CCSID 1025 NOT NULL DEFAULT '' ) ; 
  
LABEL ON TABLE RSB59TB.PARTCODE 
	IS 'PARTCODE.DBT' ; 
  
LABEL ON COLUMN RSB59TB.PARTCODE 
( PARTYID IS 'INT4' , 
	CODEKIND IS 'INT2' , 
	CODE IS 'ZSTRING' , 
	RESERVE IS 'ZSTRING' ) ; 
  
LABEL ON COLUMN RSB59TB.PARTCODE 
( PARTYID TEXT IS 'хдемрхтхйюрнп ясазейрю' , 
	CODEKIND TEXT IS 'бхд йндю' , 
	CODE TEXT IS 'йнд ясазейрю' , 
	RESERVE TEXT IS 'пегепб' ) ; 
  
