// Tie class generated by rmic, do not edit.
// Contents subject to change without notice.

package itso.ejb35.session;

import itso.ejb35.util.InsufficientFundException;
import java.io.Serializable;
import java.math.BigDecimal;
import java.rmi.Remote;
import java.rmi.RemoteException;
import javax.ejb.EJBHome;
import javax.ejb.EJBObject;
import javax.ejb.Handle;
import javax.ejb.RemoveException;
import javax.rmi.CORBA.Util;
import org.omg.CORBA.BAD_OPERATION;
import org.omg.CORBA.SystemException;
import org.omg.CORBA.portable.UnknownException;

public class _EJSRemoteStatelessTransfer_Tie extends org.omg.CORBA_2_3.portable.ObjectImpl implements javax.rmi.CORBA.Tie {
    
    private EJSRemoteStatelessTransfer target = null;
    private org.omg.CORBA.ORB orb = null;
    
    private static final String[] _type_ids = {
        "RMI:itso.ejb35.session.Transfer:0000000000000000", 
        "RMI:javax.ejb.EJBObject:0000000000000000", 
        "RMI:com.ibm.websphere.csi.CSIServant:0000000000000000", 
        "RMI:com.ibm.websphere.csi.TransactionalObject:0000000000000000"
    };
    
    public void setTarget(java.rmi.Remote target) {
        this.target = (EJSRemoteStatelessTransfer) target;
    }
    
    public java.rmi.Remote getTarget() {
        return target;
    }
    
    public org.omg.CORBA.Object thisObject() {
        return this;
    }
    
    public void deactivate() {
        if (orb != null) {
            orb.disconnect(this);
            _set_delegate(null);
        }
    }
    
    public org.omg.CORBA.ORB orb() {
        return _orb();
    }
    
    public void orb(org.omg.CORBA.ORB orb) {
        orb.connect(this);
    }
    
    public void _set_delegate(org.omg.CORBA.portable.Delegate del) {
        super._set_delegate(del);
        if (del != null)
            orb = _orb();
        else
            orb = null;
    }
    
    public String[] _ids() { 
        return _type_ids;
    }
    
    public org.omg.CORBA.portable.OutputStream _invoke(String method, org.omg.CORBA.portable.InputStream _in, org.omg.CORBA.portable.ResponseHandler reply) throws org.omg.CORBA.SystemException {
        try {
            org.omg.CORBA_2_3.portable.InputStream in = 
                (org.omg.CORBA_2_3.portable.InputStream) _in;
            switch (method.charAt(5)) {
                case 69: 
                    if (method.equals("_get_EJBHome")) {
                        EJBHome result = target.getEJBHome();
                        org.omg.CORBA.portable.OutputStream out = reply.createReply();
                        Util.writeRemoteObject(out,result);
                        return out;
                    }
                case 101: 
                    if (method.equals("remove")) {
                        try {
                            target.remove();
                        } catch (RemoveException ex) {
                            String id = "IDL:javax/ejb/RemoveEx:1.0";
                            org.omg.CORBA_2_3.portable.OutputStream out = 
                                (org.omg.CORBA_2_3.portable.OutputStream) reply.createExceptionReply();
                            out.write_string(id);
                            out.write_value(ex,RemoveException.class);
                            return out;
                        }
                        org.omg.CORBA.portable.OutputStream out = reply.createReply();
                        return out;
                    }
                case 102: 
                    if (method.equals("transferMoney")) {
                        String arg0 = (String) in.read_value(String.class);
                        String arg1 = (String) in.read_value(String.class);
                        BigDecimal arg2 = (BigDecimal) in.read_value(BigDecimal.class);
                        try {
                            target.transferMoney(arg0, arg1, arg2);
                        } catch (InsufficientFundException ex) {
                            String id = "IDL:itso/ejb35/util/InsufficientFundEx:1.0";
                            org.omg.CORBA_2_3.portable.OutputStream out = 
                                (org.omg.CORBA_2_3.portable.OutputStream) reply.createExceptionReply();
                            out.write_string(id);
                            out.write_value(ex,InsufficientFundException.class);
                            return out;
                        }
                        org.omg.CORBA.portable.OutputStream out = reply.createReply();
                        return out;
                    }
                case 104: 
                    if (method.equals("_get_handle")) {
                        Handle result = target.getHandle();
                        org.omg.CORBA.portable.OutputStream out = reply.createReply();
                        Util.writeAbstractObject(out,result);
                        return out;
                    }
                case 110: 
                    if (method.equals("isIdentical")) {
                        EJBObject arg0 = (EJBObject) in.read_Object(EJBObject.class);
                        boolean result = target.isIdentical(arg0);
                        org.omg.CORBA.portable.OutputStream out = reply.createReply();
                        out.write_boolean(result);
                        return out;
                    }
                case 112: 
                    if (method.equals("_get_primaryKey")) {
                        Object result = target.getPrimaryKey();
                        org.omg.CORBA.portable.OutputStream out = reply.createReply();
                        Util.writeAny(out,result);
                        return out;
                    }
            }
            throw new BAD_OPERATION();
        } catch (SystemException ex) {
            throw ex;
        } catch (Throwable ex) {
            throw new UnknownException(ex);
        }
    }
}
