/**
 * This class was generated by the VisualAge for Java Access Bean SmartGuide.
 * Warning:  Modifications will be lost when this part is regenerated.
 */

package itso.ejb35.bank;

import javax.ejb.*;
import javax.rmi.*;
import com.ibm.ivj.ejb.runtime.*;

public class BankingAccessBean extends com.ibm.ivj.ejb.runtime.AbstractSessionAccessBean {

    transient private itso.ejb35.bank.Banking __ejbRef = null;
 
    static final long serialVersionUID = 3206093459760846163L;

   /**
    * Zero argument constructor used to initialize the access bean.
    *
    * This constructor corresponds to the following home interface method:
    *
    * public abstract itso.ejb35.bank.Banking itso.ejb35.bank.BankingHome.create() throws javax.ejb.CreateException,java.rmi.RemoteException
    *
    */

    public BankingAccessBean () {
        super();
    }


   /**
    * This method was generated by the VisualAge for Java Access Bean SmartGuide.
    * Warning: Modifications will be lost when this part is regenerated.
    */

    public BankingAccessBean ( javax.ejb.EJBObject o ) throws java.rmi.RemoteException {
        super(o);
    }


   /**
    * This method was generated by the VisualAge for Java Access Bean SmartGuide.
    * Warning: Modifications will be lost when this part is regenerated.
    */

    protected String defaultJNDIName() {
        return "itso/ejb35/bank/Banking";
    }


   /**
    * This method was generated by the VisualAge for Java Access Bean SmartGuide.
    * Warning: Modifications will be lost when this part is regenerated.
    */

    private itso.ejb35.bank.BankingHome ejbHome() throws java.rmi.RemoteException, javax.naming.NamingException {
        return (itso.ejb35.bank.BankingHome) PortableRemoteObject.narrow(getHome(), itso.ejb35.bank.BankingHome.class);
    }


   /**
    * This method was generated by the VisualAge for Java Access Bean SmartGuide.
    * Warning: Modifications will be lost when this part is regenerated.
    */

    private itso.ejb35.bank.Banking ejbRef() throws java.rmi.RemoteException {
        if ( ejbRef == null )
            return null;
        if ( __ejbRef == null )
            __ejbRef = (itso.ejb35.bank.Banking) PortableRemoteObject.narrow(ejbRef, itso.ejb35.bank.Banking.class);

        return __ejbRef;
    }


   /**
    * This method was generated by the VisualAge for Java Access Bean SmartGuide.
    * Warning: Modifications will be lost when this part is regenerated.
    */

    protected void instantiateEJB() throws javax.ejb.CreateException, java.rmi.RemoteException, javax.naming.NamingException {
        if ( ejbRef() != null )
            return;

        ejbRef = ejbHome().create();
    }


   /**
    * This method was generated by the VisualAge for Java Access Bean SmartGuide.
    * Warning: Modifications will be lost when this part is regenerated.
    */

    public java.math.BigDecimal deposit(java.lang.String arg0, java.math.BigDecimal arg1) throws java.rmi.RemoteException, javax.ejb.CreateException, javax.naming.NamingException {

        instantiateEJB();
        return ejbRef().deposit(arg0, arg1);
    }


   /**
    * This method was generated by the VisualAge for Java Access Bean SmartGuide.
    * Warning: Modifications will be lost when this part is regenerated.
    */

    public java.math.BigDecimal getBalance(java.lang.String arg0) throws java.rmi.RemoteException, javax.ejb.CreateException, javax.naming.NamingException {

        instantiateEJB();
        return ejbRef().getBalance(arg0);
    }


   /**
    * This method was generated by the VisualAge for Java Access Bean SmartGuide.
    * Warning: Modifications will be lost when this part is regenerated.
    */

    public java.math.BigDecimal withdraw(java.lang.String arg0, java.math.BigDecimal arg1) throws java.rmi.RemoteException, itso.ejb35.util.InsufficientFundException, javax.ejb.CreateException, javax.naming.NamingException {

        instantiateEJB();
        return ejbRef().withdraw(arg0, arg1);
    }


   /**
    * This method was generated by the VisualAge for Java Access Bean SmartGuide.
    * Warning: Modifications will be lost when this part is regenerated.
    */

    public void transferMoney(java.lang.String arg0, java.lang.String arg1, java.math.BigDecimal arg2) throws java.rmi.RemoteException, itso.ejb35.util.InsufficientFundException, javax.ejb.CreateException, javax.naming.NamingException {

        instantiateEJB();
        ejbRef().transferMoney(arg0, arg1, arg2);
    }


}
