package itso.ejb35.bank;

import java.rmi.RemoteException;
import java.security.Identity;
import java.util.Properties;
import javax.ejb.*;
/**
 * This is an Entity Bean class with CMP fields
 */
public class CheckingBean extends BankAccountBean {
	public java.math.BigDecimal overdraft;
	private final static long serialVersionUID = 3206093459760846163L;

/**
 * This method was generated by the VisualAge for Java EJB AccessBean tool.
 */
/* WARNING: THIS METHOD WILL BE REGENERATED. */
public java.util.Hashtable _copyFromEJB() {
        com.ibm.ivj.ejb.runtime.AccessBeanHashtable h = new com.ibm.ivj.ejb.runtime.AccessBeanHashtable();

        h.put("overdraft", getOverdraft());
        h.put("balance", getBalance());
        h.put("__Key", getEntityContext().getPrimaryKey());

        return h;

}
/**
 * This method was generated by the VisualAge for Java EJB AccessBean tool.
 */
/* WARNING: THIS METHOD WILL BE REGENERATED. */
public void _copyToEJB(java.util.Hashtable h) {
        java.math.BigDecimal localOverdraft = (java.math.BigDecimal) h.get("overdraft");
        java.math.BigDecimal localBalance = (java.math.BigDecimal) h.get("balance");

        if ( h.containsKey("overdraft") )
            setOverdraft((localOverdraft));
        if ( h.containsKey("balance") )
            setBalance((localBalance));

}
/**
 * This method was generated for supporting the associations.
 * @return java.util.Vector
 */
/* WARNING: THIS METHOD WILL BE REGENERATED. */
protected java.util.Vector _getLinks() {
	java.util.Vector links = super._getLinks();
	return links;
}
/**
 * This method was generated for supporting the associations.
 */
/* WARNING: THIS METHOD WILL BE REGENERATED. */
protected void _initLinks() {
	super._initLinks();
}
/**
 * Insert the method's description here.
 * Creation date: (15.04.2003 16:50:05)
 * @param argAccID java.lang.String
 * @param argBalance java.math.BigDecimal
 * @exception javax.ejb.CreateException The exception description.
 * @exception java.rmi.RemoteException The exception description.
 */
public BankAccountKey ejbCreate(String argAccID, java.math.BigDecimal argBalance)
    throws javax.ejb.CreateException, javax.ejb.EJBException{
    super.ejbCreate(argAccID, argBalance);
    _initLinks();
    // All CMP fields should be initialized here.
    overdraft = new java.math.BigDecimal(200.00);
    return null;
}
/**
 * Getter method for overdraft
 * @return java.math.BigDecimal
 */
public java.math.BigDecimal getOverdraft() {
	return overdraft;
}
/**
 * Setter method for overdraft
 * @param newValue java.math.BigDecimal
 */
public void setOverdraft(java.math.BigDecimal newValue) {
	this.overdraft = newValue;
}
/**
 * Insert the method's description here.
 * Creation date: (15.04.2003 16:56:11)
 * @param amount java.math.BigDecimal
 * @exception itso.ejb35.util.InsufficientFundException The exception description.
 */
public void withdraw(java.math.BigDecimal amount) throws itso.ejb35.util.InsufficientFundException {
    System.out.println("Withdraw from " + accID + " balance " + balance + " amount " + amount);
    if (balance.add(overdraft).compareTo(amount) == -1)
        throw new itso.ejb35.util.InsufficientFundException("Not enough funds");
    else
        balance = balance.subtract(amount);
    System.out.println(" ==> new balance " + balance);
    try {
        setTxRecHome();
        txRecHomeCMP.create((BankAccount)(getEntityContext().getEJBObject()), amount, "C");
        System.out.println(" ==> transaction record created");
    }
    catch (Exception e) {
        System.out.println(" ==> transaction record failed");
        e.printStackTrace();
    }
}
}
