package itso.ejb35.bank;

import java.rmi.*;
import java.rmi.RemoteException;
import java.security.Identity;
import java.util.Properties;
import javax.ejb.*;
import javax.naming.*;
/**
 * This is an Entity Bean class with CMP fields
 */
public class CustomerBean implements EntityBean {
	public int customerID;
	private javax.ejb.EntityContext entityContext = null;
	public String firstName;
	public String lastName;
	public String password;
	private final static long serialVersionUID = 3206093459760846163L;
	public String title;
	public String userID;
	public itso.ejb35.util.CustomerAddress address;
	private transient com.ibm.ivj.ejb.associations.interfaces.ManyLink custAcctLink = null;
/**
 * This method was generated by the VisualAge for Java EJB AccessBean tool.
 */
/* WARNING: THIS METHOD WILL BE REGENERATED. */
public java.util.Hashtable _copyFromEJB() {
        com.ibm.ivj.ejb.runtime.AccessBeanHashtable h = new com.ibm.ivj.ejb.runtime.AccessBeanHashtable();

        h.put("password", getPassword());
        h.put("customerID", new Integer(getCustomerID()));
        h.put("address", getAddress());
        h.put("firstName", getFirstName());
        h.put("userID", getUserID());
        h.put("title", getTitle());
        h.put("lastName", getLastName());
        h.put("name", getName());
        h.put("__Key", getEntityContext().getPrimaryKey());

        return h;

}
/**
 * This method was generated by the VisualAge for Java EJB AccessBean tool.
 */
/* WARNING: THIS METHOD WILL BE REGENERATED. */
public void _copyToEJB(java.util.Hashtable h) {
        java.lang.String localPassword = (java.lang.String) h.get("password");
        itso.ejb35.util.CustomerAddress localAddress = (itso.ejb35.util.CustomerAddress) h.get("address");
        java.lang.String localFirstName = (java.lang.String) h.get("firstName");
        java.lang.String localUserID = (java.lang.String) h.get("userID");
        java.lang.String localTitle = (java.lang.String) h.get("title");
        java.lang.String localLastName = (java.lang.String) h.get("lastName");

        if ( h.containsKey("password") )
            setPassword((localPassword));
        if ( h.containsKey("address") )
            setAddress((localAddress));
        if ( h.containsKey("firstName") )
            setFirstName((localFirstName));
        if ( h.containsKey("userID") )
            setUserID((localUserID));
        if ( h.containsKey("title") )
            setTitle((localTitle));
        if ( h.containsKey("lastName") )
            setLastName((localLastName));

}
/**
 * This method was generated for supporting the associations.
 * @return java.util.Vector
 */
/* WARNING: THIS METHOD WILL BE REGENERATED. */
protected java.util.Vector _getLinks() {
	java.util.Vector links = new java.util.Vector();
	links.addElement(getCustAcctLink());
	return links;
}
/**
 * This method was generated for supporting the associations.
 */
/* WARNING: THIS METHOD WILL BE REGENERATED. */
protected void _initLinks() {
	custAcctLink = null;
}
/**
 * This method was generated for supporting the associations.
 * @exception java.rmi.RemoteException The exception description.
 * @exception javax.ejb.RemoveException The exception description.
 */
/* WARNING: THIS METHOD WILL BE REGENERATED. */
protected void _removeLinks() throws java.rmi.RemoteException, javax.ejb.RemoveException {
	java.util.Enumeration links = _getLinks().elements();
	while (links.hasMoreElements()) {
		try {
			((com.ibm.ivj.ejb.associations.interfaces.Link) (links.nextElement())).remove();
		}
		catch (javax.ejb.FinderException e) {} //Consume Finder error since I am going away
	}
}
/**
 * ejbActivate method comment
 * @exception java.rmi.RemoteException The exception description.
 */
public void ejbActivate() throws java.rmi.RemoteException {
	_initLinks();
}
/**
 * ejbCreate method for a CMP entity bean
 * @param argCustomerID int
 * @exception javax.ejb.CreateException The exception description.
 * @exception javax.ejb.EJBException The exception description.
 */
public CustomerKey ejbCreate(int argCustomerID) throws javax.ejb.CreateException, javax.ejb.EJBException {
    _initLinks();
    // All CMP fields should be initialized here.
    customerID = argCustomerID;
    firstName = "";
    lastName = "";
    password = "";
    title = "";
    userID = "";
    address = new itso.ejb35.util.CustomerAddress();
    return null;
}
/**
 * Insert the method's description here.
 * Creation date: (03.04.2003 12:55:05)
 * @param argCustomerID int
 * @param aTitle java.lang.String
 * @param aFirstName java.lang.String
 * @param aLastName java.lang.String
 * @param aUserID java.lang.String
 * @param aPassword java.lang.String
 * @exception javax.ejb.CreateException The exception description.
 * @exception javax.ejb.EJBException The exception description.
 */
public CustomerKey ejbCreate(
    int argCustomerID,
    String aTitle,
    String aFirstName,
    String aLastName,
    String aUserID,
    String aPassword)
    throws javax.ejb.CreateException, javax.ejb.EJBException {
    _initLinks();
    // All CMP fields should be initialized here.
    customerID = argCustomerID;
    title = aTitle;
    firstName = aFirstName;
    lastName = aLastName;
    userID = aUserID;
    password = aPassword;
    address = new itso.ejb35.util.CustomerAddress();
    return null;
}
/**
 * Insert the method's description here.
 * Creation date: (03.04.2003 12:55:05)
 * @param argCustomerID int
 * @param aTitle java.lang.String
 * @param aFirstName java.lang.String
 * @param aLastName java.lang.String
 * @param aUserID java.lang.String
 * @param aPassword java.lang.String
 * @exception javax.ejb.EJBException The exception description.
 */
public void ejbPostCreate(
    int argCustomerID,
    String aTitle,
    String aFirstName,
    String aLastName,
    String aUserID,
    String aPassword)
    throws javax.ejb.EJBException{}
/**
 * ejbLoad method comment
 * @exception java.rmi.RemoteException The exception description.
 */
public void ejbLoad() throws java.rmi.RemoteException {
	_initLinks();
}
/**
 * ejbPassivate method comment
 * @exception java.rmi.RemoteException The exception description.
 */
public void ejbPassivate() throws java.rmi.RemoteException {}
/**
 * ejbPostCreate method for a CMP entity bean
 * @param argCustomerID int
 * @exception javax.ejb.EJBException The exception description.
 */
public void ejbPostCreate(int argCustomerID) throws javax.ejb.EJBException {}
/**
 * ejbRemove method comment
 * @exception java.rmi.RemoteException The exception description.
 * @exception javax.ejb.RemoveException The exception description.
 */
public void ejbRemove() throws java.rmi.RemoteException, javax.ejb.RemoveException {
	_removeLinks();
}
/**
 * ejbStore method comment
 * @exception java.rmi.RemoteException The exception description.
 */
public void ejbStore() throws java.rmi.RemoteException {}
/**
 * Getter method for address
 */
public itso.ejb35.util.CustomerAddress getAddress() {
	return address;
}
/**
 * This method was generated for supporting the association named CustomerToAccount.  
 * 	It will be deleted/edited when the association is deleted/edited.
 */
/* WARNING: THIS METHOD WILL BE REGENERATED. */
public java.util.Enumeration getCustAcct() throws java.rmi.RemoteException, javax.ejb.FinderException {
	return this.getCustAcctLink().enumerationValue();
}
/**
 * This method was generated for supporting the association named CustomerToAccount.  
 * 	It will be deleted/edited when the association is deleted/edited.
 */
/* WARNING: THIS METHOD WILL BE REGENERATED. */
protected com.ibm.ivj.ejb.associations.interfaces.ManyLink getCustAcctLink() {
	if (custAcctLink == null)
		custAcctLink = new CustomerToCustAcctLink(this);
	return custAcctLink;
}
/**
 * Insert the method's description here.
 * Creation date: (03.04.2003 12:47:13)
 * @return int
 */
public int getCustomerID() {
    return customerID;
}
/**
 * getEntityContext method comment
 * @return javax.ejb.EntityContext
 */
public javax.ejb.EntityContext getEntityContext() {
	return entityContext;
}
/**
 * Getter method for firstName
 * @return java.lang.String
 */
public java.lang.String getFirstName() {
	return firstName;
}
/**
 * Getter method for lastName
 * @return java.lang.String
 */
public java.lang.String getLastName() {
	return lastName;
}
/**
 * Insert the method's description here.
 * Creation date: (03.04.2003 12:46:31)
 * @return java.lang.String
 */
public String getName() {
    return title.trim() + ". " + firstName.trim() + " " + lastName.trim();
}
/**
 * Getter method for password
 * @return java.lang.String
 */
public java.lang.String getPassword() {
	return password;
}
/**
 * Getter method for title
 * @return java.lang.String
 */
public java.lang.String getTitle() {
	return title;
}
/**
 * Getter method for userID
 * @return java.lang.String
 */
public java.lang.String getUserID() {
	return userID;
}
/**
 * This method was generated for supporting the association named CustomerToAccount.  
 * 	It will be deleted/edited when the association is deleted/edited.
 */
/* WARNING: THIS METHOD WILL BE REGENERATED. */
public void secondaryAddCustAcct(itso.ejb35.bank.CustAcct aCustAcct) {
	this.getCustAcctLink().secondaryAddElement(aCustAcct);
}
/**
 * This method was generated for supporting the association named CustomerToAccount.  
 * 	It will be deleted/edited when the association is deleted/edited.
 */
/* WARNING: THIS METHOD WILL BE REGENERATED. */
public void secondaryRemoveCustAcct(itso.ejb35.bank.CustAcct aCustAcct) {
	this.getCustAcctLink().secondaryRemoveElement(aCustAcct);
}
/**
 * Setter method for address
 */
public void setAddress(itso.ejb35.util.CustomerAddress newValue) {
	this.address = newValue;
}
/**
 * setEntityContext method comment
 * @param ctx javax.ejb.EntityContext
 * @exception java.rmi.RemoteException The exception description.
 */
public void setEntityContext(javax.ejb.EntityContext ctx) throws java.rmi.RemoteException {
	entityContext = ctx;
}
/**
 * Setter method for firstName
 * @param newValue java.lang.String
 */
public void setFirstName(java.lang.String newValue) {
	this.firstName = newValue;
}
/**
 * Setter method for lastName
 * @param newValue java.lang.String
 */
public void setLastName(java.lang.String newValue) {
	this.lastName = newValue;
}
/**
 * Setter method for password
 * @param newValue java.lang.String
 */
public void setPassword(java.lang.String newValue) {
	this.password = newValue;
}
/**
 * Setter method for title
 * @param newValue java.lang.String
 */
public void setTitle(java.lang.String newValue) {
	this.title = newValue;
}
/**
 * Setter method for userID
 * @param newValue java.lang.String
 */
public void setUserID(java.lang.String newValue) {
	this.userID = newValue;
}
/**
 * unsetEntityContext method comment
 * @exception java.rmi.RemoteException The exception description.
 */
public void unsetEntityContext() throws java.rmi.RemoteException {
	entityContext = null;
}
}
