/**
 * This class was generated by the VisualAge for Java Access Bean SmartGuide.
 * Warning:  Modifications will be lost when this part is regenerated.
 */

package itso.ejb35.bank;


public interface SavingsAccessBeanData {



    public java.math.BigDecimal getMinAmount() throws java.rmi.RemoteException, javax.ejb.CreateException, javax.ejb.FinderException, javax.naming.NamingException;
    public void setMinAmount( java.math.BigDecimal newValue );
    public java.math.BigDecimal getBalance() throws java.rmi.RemoteException, javax.ejb.CreateException, javax.ejb.FinderException, javax.naming.NamingException;
    public void setBalance( java.math.BigDecimal newValue );

}
