/**
 * This class was generated by the VisualAge for Java Access Bean SmartGuide.
 * Warning:  Modifications will be lost when this part is regenerated.
 */

package itso.ejb35.bank;


public interface TransRecordAccessBeanData {



    public java.lang.String getTranstype() throws java.rmi.RemoteException, javax.ejb.CreateException, javax.ejb.FinderException, javax.naming.NamingException;
    public void setTranstype( java.lang.String newValue );
    public itso.ejb35.bank.BankAccountKey getOwningAccountKey() throws java.rmi.RemoteException, javax.ejb.CreateException, javax.ejb.FinderException, javax.naming.NamingException;
    public java.math.BigDecimal getTransamt() throws java.rmi.RemoteException, javax.ejb.CreateException, javax.ejb.FinderException, javax.naming.NamingException;
    public void setTransamt( java.math.BigDecimal newValue );

}
