// Tie class generated by rmic, do not edit.
// Contents subject to change without notice.

package itso.ejb35.cmp;

import com.ibm.etools.ejb.client.runtime.FieldChangedException;
import itso.ejb35.util.CustomerAddress;
import java.io.Serializable;
import java.rmi.Remote;
import java.rmi.RemoteException;
import javax.ejb.EJBHome;
import javax.ejb.EJBObject;
import javax.ejb.Handle;
import javax.ejb.RemoveException;
import javax.rmi.CORBA.Util;
import org.omg.CORBA.BAD_OPERATION;
import org.omg.CORBA.SystemException;
import org.omg.CORBA.portable.UnknownException;

public class _EJSRemoteCMPCustomer_Tie extends org.omg.CORBA_2_3.portable.ObjectImpl implements javax.rmi.CORBA.Tie {
    
    private EJSRemoteCMPCustomer target = null;
    private org.omg.CORBA.ORB orb = null;
    
    private static final String[] _type_ids = {
        "RMI:itso.ejb35.cmp.Customer:0000000000000000", 
        "RMI:javax.ejb.EJBObject:0000000000000000", 
        "RMI:com.ibm.websphere.csi.CSIServant:0000000000000000", 
        "RMI:com.ibm.websphere.csi.TransactionalObject:0000000000000000"
    };
    
    public void setTarget(java.rmi.Remote target) {
        this.target = (EJSRemoteCMPCustomer) target;
    }
    
    public java.rmi.Remote getTarget() {
        return target;
    }
    
    public org.omg.CORBA.Object thisObject() {
        return this;
    }
    
    public void deactivate() {
        if (orb != null) {
            orb.disconnect(this);
            _set_delegate(null);
        }
    }
    
    public org.omg.CORBA.ORB orb() {
        return _orb();
    }
    
    public void orb(org.omg.CORBA.ORB orb) {
        orb.connect(this);
    }
    
    public void _set_delegate(org.omg.CORBA.portable.Delegate del) {
        super._set_delegate(del);
        if (del != null)
            orb = _orb();
        else
            orb = null;
    }
    
    public String[] _ids() { 
        return _type_ids;
    }
    
    public org.omg.CORBA.portable.OutputStream _invoke(String method, org.omg.CORBA.portable.InputStream _in, org.omg.CORBA.portable.ResponseHandler reply) throws org.omg.CORBA.SystemException {
        try {
            org.omg.CORBA_2_3.portable.InputStream in = 
                (org.omg.CORBA_2_3.portable.InputStream) _in;
            switch (method.charAt(5)) {
                case 69: 
                    if (method.equals("_get_EJBHome")) {
                        EJBHome result = target.getEJBHome();
                        org.omg.CORBA.portable.OutputStream out = reply.createReply();
                        Util.writeRemoteObject(out,result);
                        return out;
                    }
                case 97: 
                    if (method.equals("_get_address")) {
                        CustomerAddress result = target.getAddress();
                        org.omg.CORBA_2_3.portable.OutputStream out = 
                            (org.omg.CORBA_2_3.portable.OutputStream) reply.createReply();
                        out.write_value(result,CustomerAddress.class);
                        return out;
                    } else if (method.equals("_set_address")) {
                        CustomerAddress arg0 = (CustomerAddress) in.read_value(CustomerAddress.class);
                        target.setAddress(arg0);
                        org.omg.CORBA.portable.OutputStream out = reply.createReply();
                        return out;
                    }
                case 99: 
                    if (method.equals("_get_customerID")) {
                        int result = target.getCustomerID();
                        org.omg.CORBA.portable.OutputStream out = reply.createReply();
                        out.write_long(result);
                        return out;
                    } else if (method.equals("_get_customerData")) {
                        CustomerData result = target.getCustomerData();
                        org.omg.CORBA_2_3.portable.OutputStream out = 
                            (org.omg.CORBA_2_3.portable.OutputStream) reply.createReply();
                        out.write_value(result,CustomerData.class);
                        return out;
                    }
                case 101: 
                    if (method.equals("remove")) {
                        try {
                            target.remove();
                        } catch (RemoveException ex) {
                            String id = "IDL:javax/ejb/RemoveEx:1.0";
                            org.omg.CORBA_2_3.portable.OutputStream out = 
                                (org.omg.CORBA_2_3.portable.OutputStream) reply.createExceptionReply();
                            out.write_string(id);
                            out.write_value(ex,RemoveException.class);
                            return out;
                        }
                        org.omg.CORBA.portable.OutputStream out = reply.createReply();
                        return out;
                    }
                case 102: 
                    if (method.equals("_get_firstName")) {
                        String result = target.getFirstName();
                        org.omg.CORBA_2_3.portable.OutputStream out = 
                            (org.omg.CORBA_2_3.portable.OutputStream) reply.createReply();
                        out.write_value(result,String.class);
                        return out;
                    } else if (method.equals("_set_firstName")) {
                        String arg0 = (String) in.read_value(String.class);
                        target.setFirstName(arg0);
                        org.omg.CORBA.portable.OutputStream out = reply.createReply();
                        return out;
                    }
                case 104: 
                    if (method.equals("_get_handle")) {
                        Handle result = target.getHandle();
                        org.omg.CORBA.portable.OutputStream out = reply.createReply();
                        Util.writeAbstractObject(out,result);
                        return out;
                    }
                case 108: 
                    if (method.equals("_get_lastName")) {
                        String result = target.getLastName();
                        org.omg.CORBA_2_3.portable.OutputStream out = 
                            (org.omg.CORBA_2_3.portable.OutputStream) reply.createReply();
                        out.write_value(result,String.class);
                        return out;
                    } else if (method.equals("_set_lastName")) {
                        String arg0 = (String) in.read_value(String.class);
                        target.setLastName(arg0);
                        org.omg.CORBA.portable.OutputStream out = reply.createReply();
                        return out;
                    }
                case 110: 
                    if (method.equals("isIdentical")) {
                        EJBObject arg0 = (EJBObject) in.read_Object(EJBObject.class);
                        boolean result = target.isIdentical(arg0);
                        org.omg.CORBA.portable.OutputStream out = reply.createReply();
                        out.write_boolean(result);
                        return out;
                    } else if (method.equals("_get_name")) {
                        String result = target.getName();
                        org.omg.CORBA_2_3.portable.OutputStream out = 
                            (org.omg.CORBA_2_3.portable.OutputStream) reply.createReply();
                        out.write_value(result,String.class);
                        return out;
                    }
                case 112: 
                    if (method.equals("_get_primaryKey")) {
                        Object result = target.getPrimaryKey();
                        org.omg.CORBA.portable.OutputStream out = reply.createReply();
                        Util.writeAny(out,result);
                        return out;
                    } else if (method.equals("_get_password")) {
                        String result = target.getPassword();
                        org.omg.CORBA_2_3.portable.OutputStream out = 
                            (org.omg.CORBA_2_3.portable.OutputStream) reply.createReply();
                        out.write_value(result,String.class);
                        return out;
                    } else if (method.equals("_set_password")) {
                        String arg0 = (String) in.read_value(String.class);
                        target.setPassword(arg0);
                        org.omg.CORBA.portable.OutputStream out = reply.createReply();
                        return out;
                    }
                case 115: 
                    if (method.equals("setCustomerData")) {
                        CustomerData arg0 = (CustomerData) in.read_value(CustomerData.class);
                        try {
                            target.setCustomerData(arg0);
                        } catch (FieldChangedException ex) {
                            String id = "IDL:com/ibm/etools/ejb/client/runtime/FieldChangedEx:1.0";
                            org.omg.CORBA_2_3.portable.OutputStream out = 
                                (org.omg.CORBA_2_3.portable.OutputStream) reply.createExceptionReply();
                            out.write_string(id);
                            out.write_value(ex,FieldChangedException.class);
                            return out;
                        }
                        org.omg.CORBA.portable.OutputStream out = reply.createReply();
                        return out;
                    }
                case 116: 
                    if (method.equals("_get_title")) {
                        String result = target.getTitle();
                        org.omg.CORBA_2_3.portable.OutputStream out = 
                            (org.omg.CORBA_2_3.portable.OutputStream) reply.createReply();
                        out.write_value(result,String.class);
                        return out;
                    } else if (method.equals("_set_title")) {
                        String arg0 = (String) in.read_value(String.class);
                        target.setTitle(arg0);
                        org.omg.CORBA.portable.OutputStream out = reply.createReply();
                        return out;
                    }
                case 117: 
                    if (method.equals("_get_userID")) {
                        String result = target.getUserID();
                        org.omg.CORBA_2_3.portable.OutputStream out = 
                            (org.omg.CORBA_2_3.portable.OutputStream) reply.createReply();
                        out.write_value(result,String.class);
                        return out;
                    } else if (method.equals("_set_userID")) {
                        String arg0 = (String) in.read_value(String.class);
                        target.setUserID(arg0);
                        org.omg.CORBA.portable.OutputStream out = reply.createReply();
                        return out;
                    } else if (method.equals("syncCustomerData")) {
                        CustomerData arg0 = (CustomerData) in.read_value(CustomerData.class);
                        CustomerData result = target.syncCustomerData(arg0);
                        org.omg.CORBA_2_3.portable.OutputStream out = 
                            (org.omg.CORBA_2_3.portable.OutputStream) reply.createReply();
                        out.write_value(result,CustomerData.class);
                        return out;
                    }
            }
            throw new BAD_OPERATION();
        } catch (SystemException ex) {
            throw ex;
        } catch (Throwable ex) {
            throw new UnknownException(ex);
        }
    }
}
