INSERT INTO
   ILDAR.CLIENTS
   (
      INN_CLN,
      OKPO,
      NAME_CLN,
      FIO_CLN,
      PHONE_CLN,
      ADDR_CLN,
      NUM_DOGOV,
      REG_DATE,
      PERMS,
      LOCK_WORD,
      STATUS,
      CLN_TYPE,
      DOC_SIGN_NUM
   )
    VALUES
   (
      'ИНН 1',
      'ОКПО',
      'Наименование клиента 1',
      'ФИО 1',
      'ТЕЛЕФОН 1',
      'АДРЕСС 1',
      '1',
      '23.08.2002',
      1,
      'ПОПАЛ',
      2,
      0,
      000
   )